#!/bin/bash
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /clone ensure=absent force=true
puppet resource file / ensure=directory
puppet resource file /clone ensure=directory
cd /clone
git clone https://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@github.com/mfbsh/operate_repo.git
cp -p /operate_repo/index.html /var/www/html
